build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    complexity: 1
    exceptions: 1
    style: 1
    comments: 1
    empty-blocks: 1
    naming : 1
    formatting : 1
    performance : 1
    potential-bugs : 1
    coroutines : 1

config:
  validation: true
  warningsAsErrors: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'
  # - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    #  - 'FindingsReport'
    - 'FileBasedFindingsReport'
    - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
    # - 'TxtOutputReport'
    # - 'XmlOutputReport'
    # - 'HtmlOutputReport'
    - 'MdOutputReport'


comments: {}

complexity:
  LargeClass:
    excludes: &excludePaths
      - '**/test/**'
      - '**/androidTest/**'
  #    - '**/component_catalog/**'
  LongMethod:
    excludes: *excludePaths
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    ignoreAnnotated:
      - 'Inject'
      - 'AssistedInject'
      - 'Binds'
      - 'Provides'
      - 'Composable'
    excludes:
      - '**/lib/**' # In lib modules, can't `@Inject`; while using `@Suppress` may be cumbersome.
      - '**/test/**'
      - '**/androidTest/**'
      - '**/debug/**'
  TooManyFunctions:
    active: false # We love many functions?

coroutines: {}

empty-blocks: {}

exceptions: {}

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Test' # AN APPROACH to https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods.
      - 'Composable' # AN APPROACH to Compose style.
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*|[A-Z][A-Za-z0-9]*' # AN APPROACH to Compose style.

performance: {}

potential-bugs:
  UnsafeCallOnNullableType:
    excludes: *excludePaths

style:
  FunctionOnlyReturningConstant:
    excludedFunctions: ['describeContents']
    ignoreAnnotated: ['Provides']
  MagicNumber:
    active: false
  MaxLineLength:
    excludes: *excludePaths
  ReturnCount:
    excludeGuardClauses: true
  ThrowsCount:
    excludeGuardClauses: true
  UnnecessaryAbstractClass:
    excludes: *excludePaths # Some base test classes are intended only to be subclassed.
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview' # AN APPROACH for Compose preview.
  WildcardImport:
    excludes: ['**/di/**']
    excludeImports: # `java.util.*` isn't excluded because some names collides with Kotlin ones.
      - 'kotlinx.android.synthetic.*'

formatting:
  ArgumentListWrapping:
    active: false # Group multiple closely related arguments on the same line (https://kotlinlang.org/docs/coding-conventions.html).
  Filename:
    active: false # Overlaps with `naming>MatchingDeclarationName`.
  FinalNewline:
    active: false # Overlaps with `style>NewLineAtEndOfFile`.
  ImportOrdering:
    active: false
  MaximumLineLength:
    active: false # Overlaps with `style>MaxLineLength`.
  ModifierOrdering:
    active: false # Overlaps with `style>ModifierOrder`.
  NoWildcardImports:
    active: false # Overlaps with `style>WildcardImport` (but the doc doesn't mention it).
