name: Run Detekt

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: '21'
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Detekt
        run: ./gradlew detekt --no-daemon --stacktrace

      - name: Run Detekt
        run: ./gradlew detekt
