name: Run Detekt On Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  detekt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Detekt
        run: ./gradlew detekt --no-daemon --stacktrace

      - name: Run Detekt
        run: ./gradlew detekt
