name: Run Detekt On Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  detekt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt -Pauto-correct html --output build/reports/detekt/detekt-report.html

      - name: Upload Detekt Report to Github PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Detekt Report
            Detekt has finished running. Please check the [full report](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/build/reports/detekt/detekt-report.html) for details.
          
            ### Detekt Issues:
            ```bash
            $(cat build/reports/detekt/detekt-report.html | grep -oP '(?<=<p>)(.*?)(?=</p>)')
            ```

      - name: Fail the build if Detekt has errors
        run: |
          if grep -q 'error' build/reports/detekt/detekt-report.html; then
            exit 1
          fi
